- name: nginx 
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: ansent
  - name: start nginx
    # ansible.builtin.service:
    #   name: nginx
    #   state: started
