- name: variable and ini
  hosts: local
  connection: local
  vars:
   GREET: play
  vars_prompt:
   - name: GREET
     prompt: enter your greet
     private: false
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello form {{ GREET }}"
