- name: datatypes
  hosts: local
  connection: local
  vars:
    Course: devops with aws
    Duration: 120
    topics:
    - linux
    - ansible
    - shell
    tools:
      ci: jenkins
      cloud: aws
      conteraization: docker
    live: true
  tasks:
   - name: print the datatypes
     ansible.builtin.debug:
       msg: "Course is {{ Course }}, Duration is {{ Duration }}, topics are {{ topics }}, tools are {{ tools }}, is it live?{{ live }},"