- name: Devops course information
  hosts: local
  connection: local
  vars:
    course_name: "Devops with aws"
    duration: 120
    topics:
    - linux
    - shell
    - ansible
    - aws
    live: true
    tools:
      ci: jenkins
      cloud: aws
      conteraization: docker
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Course is {{ course_name }}, Duration is {{ duration }}, topics are {{ topics }}, is it live? {{ live }}, tools are {{ tools }} "