- name: conditions
  hosts: local
  connection: local
  vars:
    my_number: 15
  tasks:
  - name: print the number if it greater
    ansible.builtin.debug:
      msg: "Number {{ my_number }} is greater than 10"
    when: my_number > 10
