- name: filters
  hosts: local
  connection: local
  tasks:
  - name: undefinded veriables
    ansible.builtin.debug:
      msg: "Hello from {{ person | default('ramesh')}}"

  - name: convet string in list
    vars:
      fruits: "apple, banana, mango"
    ansible.builtin.debug:
      msg: "Fruits are: {{ fruits | split(',') }}"

  - name: convet list in maps
    vars:
      course:
        name: devops
        duration: 120
        trainer: rabbani
    ansible.builtin.debug:
      msg: "Course info: {{ course | dict2items }}"

  - name: convet maps to list
    vars: 
      course: 
        - {'key': 'name', 'value': 'devops'}
        - {'key': 'duration', 'value': 120}
        - {'key': 'trainer', 'value': 'rabbani'}
    ansible.builtin.debug:
      msg: "Course info: {{ course | items2dict }}"

  - name: check Ip is correct
    vars: 
      Ip : 234.65.767.788
    ansible.builtin.debug:
      msg: "{{ Ip | ansible.utils.ipaddr }}"
  
