- name: filters
  hosts: local
  connection: local
  tasks:
  - name: undefinded veriables
    ansible.builtin.debug:
      msg: Hello from "{{ person | default('ramesh')}}"

  - name: convet string in list
    vars:
      fruits: " apple, banana, mango"
    ansible.builtin.debug:
      msg: Fruits are: "{{ fruits | split(',') }}"
  
