- name: filters
  hosts: local
  connection: local
  vars:
    fruits:" apple, banana, mango"
  tasks:
  - name: undefinded veriables
    ansible.builtin.debug:
      msg: Hello from | {{ default('ramesh')}}

  tasks:
  - name: convet string in list
    ansible.builtin.debug:
      msg: fruits are "{{ fruits | split(','')}}"
  
