- name: command vs shell
  hosts: local
  connection: local
  tasks:
    - name: execute command
      ansible.builtin.command: ls -ltr 
      # ansible.builtin.shell: ls -ltr > /tmp/output.txt
      register: command_result

    - name: print the output
      ansible.builtin.debug:
        msg: "{{ command_result }}"