- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    instance_type: t3.micro
    image_id: ami-0220d79f3f480ecf5
    vpc_subnet_id: vpc-042e82ca983316f90
    sg_id: sg-0a9372f8a692ed98f
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: install libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore

  - name: create ec2
    amazon.aws.ec2_instance:
    name: "{{ item }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ image_id }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    security_group: "{{ sg_id }}"
    loop: "{{ instances }}"
