- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    instance_type: t3.micro
    image_id: ami-0220d79f3f480ecf5
    vpc_subnet_id: subnet-02fef984c3041a40e
    sg_id: sg-0a9372f8a692ed98f
    zone: awsdevsecops.online
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: install libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore

  - name: create ec2
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: "{{ instance_type }}"
      image_id: "{{ image_id }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      security_group: "{{ sg_id }}"
    loop: "{{ instances }}"
    register: ec2_info

  - name: print the result
    ansible.builtin.debug:
      msg: "{{ ec2_info }}"

  - name: print private ip private Ip
    ansible.builtin.debug:
      msg: "{{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_info.results }}"

  - name: create r53
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true 
    loop: "{{ ec2_info }}"
