- name: create ec2 and r53 
  connection: local
  hosts: local
  vars:
    subnet_id: subnet-02fef984c3041a40e
    ami_id: ami-0220d79f3f480ecf5
    sg_id: sgr-0e40dfcf5e24fbb1c
    instance_type: t3.micro
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: install pip libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "{{ instance_type }}"
      image_id: "{{ ami_id }}"
      security_group: "{{ sg_id }}"
    loop: "{{ instances }}"