[web]
172.31.31.110 COURSE= aws with devops DURATION= 120HRS TRAINER= Rabbani ansible_user=ec2-user ansible_password=DevOps321
localhost 

[local]
localhost

[local:vars]
COURSE= aws with devops
DURATION= 120HRS
TRAINER= Rabbani